// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: src/proto/SysInfo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MonitorServiceClient is the client API for MonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitorServiceClient interface {
	StaticService(ctx context.Context, in *StaticInfo, opts ...grpc.CallOption) (*ResponseStatus, error)
	DynamicService(ctx context.Context, in *DynamicInfo, opts ...grpc.CallOption) (*ResponseStatus, error)
	NetDelayService(ctx context.Context, in *NetDelayInfo, opts ...grpc.CallOption) (*ResponseStatus, error)
	ReportService(ctx context.Context, in *ClientReport, opts ...grpc.CallOption) (*ResponseStatus, error)
}

type monitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorServiceClient(cc grpc.ClientConnInterface) MonitorServiceClient {
	return &monitorServiceClient{cc}
}

func (c *monitorServiceClient) StaticService(ctx context.Context, in *StaticInfo, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/sysInfo.MonitorService/StaticService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) DynamicService(ctx context.Context, in *DynamicInfo, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/sysInfo.MonitorService/DynamicService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) NetDelayService(ctx context.Context, in *NetDelayInfo, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/sysInfo.MonitorService/NetDelayService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) ReportService(ctx context.Context, in *ClientReport, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/sysInfo.MonitorService/reportService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServiceServer is the server API for MonitorService service.
// All implementations must embed UnimplementedMonitorServiceServer
// for forward compatibility
type MonitorServiceServer interface {
	StaticService(context.Context, *StaticInfo) (*ResponseStatus, error)
	DynamicService(context.Context, *DynamicInfo) (*ResponseStatus, error)
	NetDelayService(context.Context, *NetDelayInfo) (*ResponseStatus, error)
	ReportService(context.Context, *ClientReport) (*ResponseStatus, error)
	mustEmbedUnimplementedMonitorServiceServer()
}

// UnimplementedMonitorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMonitorServiceServer struct {
}

func (UnimplementedMonitorServiceServer) StaticService(context.Context, *StaticInfo) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StaticService not implemented")
}
func (UnimplementedMonitorServiceServer) DynamicService(context.Context, *DynamicInfo) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DynamicService not implemented")
}
func (UnimplementedMonitorServiceServer) NetDelayService(context.Context, *NetDelayInfo) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetDelayService not implemented")
}
func (UnimplementedMonitorServiceServer) ReportService(context.Context, *ClientReport) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportService not implemented")
}
func (UnimplementedMonitorServiceServer) mustEmbedUnimplementedMonitorServiceServer() {}

// UnsafeMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServiceServer will
// result in compilation errors.
type UnsafeMonitorServiceServer interface {
	mustEmbedUnimplementedMonitorServiceServer()
}

func RegisterMonitorServiceServer(s grpc.ServiceRegistrar, srv MonitorServiceServer) {
	s.RegisterService(&MonitorService_ServiceDesc, srv)
}

func _MonitorService_StaticService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).StaticService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysInfo.MonitorService/StaticService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).StaticService(ctx, req.(*StaticInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_DynamicService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DynamicInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).DynamicService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysInfo.MonitorService/DynamicService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).DynamicService(ctx, req.(*DynamicInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_NetDelayService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetDelayInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).NetDelayService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysInfo.MonitorService/NetDelayService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).NetDelayService(ctx, req.(*NetDelayInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_ReportService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ReportService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysInfo.MonitorService/reportService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ReportService(ctx, req.(*ClientReport))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitorService_ServiceDesc is the grpc.ServiceDesc for MonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysInfo.MonitorService",
	HandlerType: (*MonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StaticService",
			Handler:    _MonitorService_StaticService_Handler,
		},
		{
			MethodName: "DynamicService",
			Handler:    _MonitorService_DynamicService_Handler,
		},
		{
			MethodName: "NetDelayService",
			Handler:    _MonitorService_NetDelayService_Handler,
		},
		{
			MethodName: "reportService",
			Handler:    _MonitorService_ReportService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/SysInfo.proto",
}
